In [9]:
%%HTML
<style type="text/css">
table.dataframe td, table.dataframe th {
    border: 1px  black solid !important;
  color: black !important;
}
</style>

In [6]:
# Import Libraries
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [7]:
# Import Dataset
dataset = pd.read_csv("./data/covid.csv")

In [11]:
# Look dataset
dataset

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,China,2020-03-11T10:53:02,67773,3046,49134,30.9756,112.2707
1,NaN,Italy,2020-03-11T21:33:02,12462,827,1045,43.0000,12.0000
2,NaN,Iran,2020-03-11T18:52:03,9000,354,2959,32.0000,53.0000
3,NaN,"Korea, South",2020-03-11T21:13:18,7755,60,288,36.0000,128.0000
4,France,France,2020-03-11T22:53:03,2281,48,12,46.2276,2.2137
...,...,...,...,...,...,...,...,...
211,Mississippi,US,2020-03-10T02:33:04,0,0,0,32.7416,-89.6787
212,North Dakota,US,2020-03-10T02:33:04,0,0,0,47.5289,-99.7840
213,West Virginia,US,2020-03-10T02:33:04,0,0,0,38.4912,-80.9545
214,Wyoming,US,2020-03-10T02:33:04,0,0,0,42.7560,-107.3025
215,NaN,occupied Palestinian territory,2020-03-11T20:53:02,0,0,0,31.9522,35.2332

In [ ]:
x = dataset.iloc[:,]